//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'model_cache.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelCache extends _ModelCache {
  //
  //
  //

  static const CLASS = 'ModelCache';
  static const MODEL_ID = 'model_cache';

  static const K_DART_SDK_PATH = 'dart_sdk_path';
  static const K_GENERATE_MODEL_SETTINGS = 'generate_model_settings';
  static const K_GENERATE_SCREEN_SETTINGS = 'generate_screen_settings';
  static const K_ID = 'id';
  static const K_INITIAL_SCREEN_PATH = 'initial_screen_path';
  static const K_PROJECT_ROOT_DIR_PATH = 'project_root_dir_path';
  static const K_TEMPLATES_DIR_PATH = 'templates_dir_path';

  String? dartSdkPath;
  ModelGenerateModelSettings? generateModelSettings;
  ModelGenerateScreenSettings? generateScreenSettings;
  String? initialScreenPath;
  String? projectRootDirPath;
  String? templatesDirPath;

  //
  //
  //

  ModelCache({
    String? id,
    this.dartSdkPath,
    this.generateModelSettings,
    this.generateScreenSettings,
    this.initialScreenPath,
    this.projectRootDirPath,
    this.templatesDirPath,
  }) {
    this.id = id;
  }

  //
  //
  //

  ModelCache.unsafe({
    String? id,
    this.dartSdkPath,
    this.generateModelSettings,
    this.generateScreenSettings,
    this.initialScreenPath,
    this.projectRootDirPath,
    this.templatesDirPath,
  }) {
    this.id = id;
  }

  //
  //
  //

  factory ModelCache.from(
    Model? other,
  ) {
    return ModelCache.unsafe()..updateWith(other);
  }

  //
  //
  //

  factory ModelCache.of(
    ModelCache? other,
  ) {
    return ModelCache.unsafe()..updateWith(other);
  }

  //
  //
  //

  factory ModelCache.fromJsonString(
    String? source,
  ) {
    try {
      if (source != null && source.isNotEmpty) {
        final decoded = jsonDecode(source);
        return ModelCache.fromJson(decoded);
      } else {
        return ModelCache.unsafe();
      }
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  factory ModelCache.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return ModelCache.unsafe(
        dartSdkPath: otherData?[K_DART_SDK_PATH]?.toString().trim().nullIfEmpty,
        generateModelSettings: () {
          final a =
              letMap<String, dynamic>(otherData?[K_GENERATE_MODEL_SETTINGS]);
          return a != null ? ModelGenerateModelSettings.fromJson(a) : null;
        }(),
        generateScreenSettings: () {
          final a =
              letMap<String, dynamic>(otherData?[K_GENERATE_SCREEN_SETTINGS]);
          return a != null ? ModelGenerateScreenSettings.fromJson(a) : null;
        }(),
        id: otherData?[K_ID]?.toString().trim().nullIfEmpty,
        initialScreenPath:
            otherData?[K_INITIAL_SCREEN_PATH]?.toString().trim().nullIfEmpty,
        projectRootDirPath:
            otherData?[K_PROJECT_ROOT_DIR_PATH]?.toString().trim().nullIfEmpty,
        templatesDirPath:
            otherData?[K_TEMPLATES_DIR_PATH]?.toString().trim().nullIfEmpty,
      );
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final withNulls = <String, dynamic>{
        K_DART_SDK_PATH: dartSdkPath?.toString().trim().nullIfEmpty,
        K_GENERATE_MODEL_SETTINGS: generateModelSettings?.toJson(),
        K_GENERATE_SCREEN_SETTINGS: generateScreenSettings?.toJson(),
        K_ID: id?.toString().trim().nullIfEmpty,
        K_INITIAL_SCREEN_PATH: initialScreenPath?.toString().trim().nullIfEmpty,
        K_PROJECT_ROOT_DIR_PATH:
            projectRootDirPath?.toString().trim().nullIfEmpty,
        K_TEMPLATES_DIR_PATH: templatesDirPath?.toString().trim().nullIfEmpty,
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  @override
  T empty<T extends Model>() {
    return ModelCache.unsafe() as T;
  }

  //
  //
  //

  @override
  T copy<T extends Model>() {
    return (ModelCache.unsafe()..updateWith(this)) as T;
  }

  //
  //
  //

  @override
  void updateWithJson(
    Map<String, dynamic>? otherData,
  ) {
    if (otherData != null && otherData.isNotEmpty) {
      final other = ModelCache.fromJson(otherData);
      other.dartSdkPath != null ? this.dartSdkPath = other.dartSdkPath : null;
      other.generateModelSettings != null
          ? this.generateModelSettings = other.generateModelSettings
          : null;
      other.generateScreenSettings != null
          ? this.generateScreenSettings = other.generateScreenSettings
          : null;
      other.id != null ? this.id = other.id : null;
      other.initialScreenPath != null
          ? this.initialScreenPath = other.initialScreenPath
          : null;
      other.projectRootDirPath != null
          ? this.projectRootDirPath = other.projectRootDirPath
          : null;
      other.templatesDirPath != null
          ? this.templatesDirPath = other.templatesDirPath
          : null;
    }
  }
}
