//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// X|Y|Z & Dev
//
// Copyright Ⓒ Robert Mollentze, xyzand.dev
//
// Licensing details can be found in the LICENSE file in the root directory.
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

import '/_common.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

String createAnnotatedClassFileContent(
  ModelGenerateModelSettings settings,
) {
  final directives = settings.getDirectives();
  final className = settings.getClassName();
  final generatedFileName = settings.getGeneratedModelFileName();
  final keyStringCase = settings.getKeyStringCase().name;
  final includeId = settings.getIncludeId();
  final includeArgs = settings.getIncludeArgs();
  final superClass = settings.getSuperClassName() != 'None'
      ? settings.getSuperClassName()
      : '';
  final fieldEntries = settings.getFieldEntries();

  final insertFields = () {
    final fieldNames = fieldEntries.map((e) => e.fieldName).nonNulls;
    final uniqueEntries =
        fieldNames.map((a) => fieldEntries.firstWhere((b) => b.fieldName == a));
    final temp = uniqueEntries.map(
      (e) {
        var fieldName = e.fieldName;
        fieldName = fieldName != null
            ? StringCaseType.values
                .valueOf(keyStringCase)
                ?.convertString(fieldName)
            : null;
        return "'$fieldName': '${e.fieldType!.replaceLast(RegExp('\\?+'), '')}${e.isNullable! ? '?' : ''}'";
      },
    );
    return "${temp.join(',\n')}${temp.isNotEmpty ? ',' : ''}";
  }();
  final insertShouldInheret =
      superClass.isNotEmpty ? 'shouldInherit: true,' : '';
  final insertKeyStringCase = keyStringCase == 'LOWER_SNAKE_CASE'
      ? ''
      : "keyStringCase: '$keyStringCase',";
  final insertIncludeId = includeId ? '' : 'includeId: false,';
  final insertIncludeArgs = includeArgs ? 'includeArgs: true,' : '';
  final insertExtends = superClass.isNotEmpty ? 'extends $superClass' : '';
  return '''
  //.title
  // ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
  //
  // GENERATED BY XYZ_GENIE
  // See: https://github.com/robmllze/xyz_gen
  //
  // ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
  //.title~

  import 'package:xyz_gen_annotations/xyz_gen_annotations.dart';

  ${directives.join('\n')}

  part '$generatedFileName';

  // ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

  @GenerateModel(
    fields: {
      $insertFields
    },
    $insertShouldInheret
    $insertKeyStringCase
    $insertIncludeId
    $insertIncludeArgs
  )
  // ignore: unused_element
  abstract class _$className $insertExtends {}
  ''';
}
