##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## 🇽🇾🇿 & Dev
##
## Licencing details are in the LICENSE file in the root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: xyz_genie_app
description: A visual tool to operate the generators from the xyz_gen package and help you with your Flutter projects.
repository: https://github.com/robmllze/xyz_genie
publish_to: none
version: 0.1.0+1

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.3.1 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter

  _data:
    path: ../../_data
  _service_interfaces:
    path: ../../_service_interfaces
  _services:
    path: ../../_services
  _view:
    path: ../../_view

  xyz_config: ^0.28.0
  xyz_flutter_plus: ^0.41.3
  xyz_gen_annotations: ^0.15.2
  xyz_gen: ^0.56.0
  xyz_pod: ^0.24.0
  xyz_utils: ^0.52.0

  google_fonts: any
  file_picker: ^6.1.1
  fluentui_system_icons: any
  cupertino_icons: ^1.0.2

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

## -----------------------------------------------------------------------------

flutter:
  uses-material-design: true

  # assets:
  #   - assets/
  #   - assets/translations/
