//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GENIE
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

import '/_common.dart';

part '_model_generate_screen_settings.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

@GenerateModel(
  fields: {
    'class_name': 'String?',
    'default_title': 'String?',
    'makeup': 'String?',
    'navigation_control_widget': 'String?',
    'internal_parameters': 'Map<String, String>?',
    'query_parameters': 'Set<String>?',
    'is_only_accessible_if_logged_in_and_verified': 'bool?',
    'is_only_accessible_if_logged_in': 'bool?',
    'is_only_accessible_if_logged_out': 'bool?',
    'email': 'String?',
  },
  shouldInherit: true,
)
// ignore: unused_element
abstract class _ModelGenerateScreenSettings
    extends ThisModel<ModelGenerateScreenSettings> {}
